
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/stock_example
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            jdbc:
              BasicBinder: TRACE